### ISSUE TITLE
Server stack after 16363 requests (+-10)

### ISSUE THREAD

**Issue by Paxa** [cesanta/mongoose#443] opened 2014-11-20 19:38 UTC
OS: mac 10.9
```
% gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```
* I compile example from `examples/multi_threaded_server`
* run it as `./multi_threaded_server`
* run benchmark

    ab -n 50000 -c 10 http://127.0.0.1:8080/

It stacks at 16363th request

I wrote simple script in ruby to do same (sending requests):

```ruby
require 'net/http'

20_000.times do |i|
  begin
    puts "done #{i}" if i % 1000 == 0
    result = Net::HTTP.get(URI.parse('http://127.0.0.1:8080/'))
  rescue => e
    puts "Failed on #{i}"
    raise e
  end
end
```

And get error:
```
...
done 14000
done 15000
done 16000
Failed on 16368
/Users/pavel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Can't assign requested address - connect(2) for "127.0.0.1" port 8080 (Errno::EADDRNOTAVAIL)
```

Then run with curl:
```
% curl http://localhost:8080/
curl: (7) Failed to connect to 127.0.0.1: Can't assign requested address
```

Then wait few seconds and it working again (without restarting a server)

**Comment by cpq** [comment] 2015-03-21 13:19
Closing this, please reopen if you reckon the problem is with mongoose.

**Closed by cpq** 2015-03-21 13:19 UTC
