### ISSUE TITLE
MQTT Broker doesn't handle more than one message in single TCP Packet

### ISSUE THREAD

**Issue by rozpuszczalny** [cesanta/mongoose#825] opened 2017-06-23 10:17 UTC
Hello,

I'm trying to achieve simple goal - write program, which accepts some TCP connection, gets packets from this connection, and publish these packets in MQTT topic; moreover, this program internally can send MQTT messages. This program also acts as a MQTT broker, using mongoose mqtt broker.

When I've written a small PoC, I noticed, that some messages doesn't pass to MQTT topic, but it passes TCP connection. However, this lost message appears, when another messages is pushed to MQTT topic. But then - a new messages is not shown, until I repeat the process.

So I stared to test it. Created a program which:
1. Create MQTT broker on port 54321
2. Create MQTT client to address localhost:54321
3. Listen TCP connections on port 12345
4. Publish MQTT message to broker every 1.4s, up to 5 messages

Before program run, I ran Wireshark, to analyze net traffic.

During program run, I'm connecting through telnet to port 12345, and send bunch of random packets (random = rage keyboard strikes ;) ). Problem occured on first try.

Based on Wireshark capture and printf's, followed happend:
1. MQTT Client connected to MQTT Broker
2. Program published message "`val0`"
3. Broker published back message "`val0`"
4. Program published message "`val1`"
5. Broker published back message "`val1`"
6. I've opened TCP connection with port 12345, and send message "`asdgasd\r\n`"
7. In the (almost) same time, program ran mg_mqtt_publish to broker with message "`val2`"
8. **MQTT Client published two MQTT messages: "`asdgasd\r\n`" and "`val2`" using single TCP packet** _(Frame no 29)_
9. **Broker published back message "`asdgasd\r\n`"** _(Frame no 31)_
10. Send message "`asjasd\r\n`" through TCP connection
11. Program published "`asjasd\r\n`" to broker _(Frame no 35)_
12. **Broker published back message "`val2`"** _(Frame no 37)_
...and more steps are seen in attached pcap file.

STDOUT: [mongoose-mqtt-broker-stdout.txt](https://github.com/cesanta/mongoose/files/1097460/mongoose-mqtt-broker-stdout.txt)
PCAP File: [mongoose-mqtt-broker.pcap.gz](https://github.com/cesanta/mongoose/files/1097452/mongoose-mqtt-broker.pcap.gz)

In my opinion, broker should break these messages, and publish them as separate messages.

Compiled with `clang++ --std=c++11 mongoose.c test.c -Wunused -D MG_ENABLE_MQTT_BROKER=1 -D CS_ENABLE_DEBUG=1`

```
$ clang++ --version
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

System: MacOS 10.12.4

Test code (ignore nasty printf with connection pointers ;) )

```c
#include "mongoose.h"

static struct mg_connection *mqtt_nc = NULL;

uint8_t is_subed = 0x00;

// Callback TCP mongoose
static void ev_tcp_handler(struct mg_connection *nc, int ev, void *p)
{
    (void)p;
    switch (ev)
    {
    case MG_EV_RECV:
        struct mbuf *io = &nc->recv_mbuf;
        char *teh = (char *)malloc(sizeof(char) * (io->len + 1));

        strncpy(teh, io->buf, io->len);
        teh[io->len] = 0;

        printf("Got from tcp %s\r\n", teh);
        if (mqtt_nc != NULL)
        {
            printf("Publishing from tcp %s\r\n", teh);
            mg_mqtt_publish(mqtt_nc, "/test", 0, MG_MQTT_QOS(0), io->buf, io->len);
        }

        // Release buffer
        mbuf_remove(io, io->len);
        free(teh);
        break;
    }
}
time_t last_ping;

void ev_handler(struct mg_connection *nc, int ev, void *p)
{
    struct mg_mqtt_message *msg = (struct mg_mqtt_message *)p;
    (void)nc;

    switch (ev)
    {
    case MG_EV_CONNECT:
    {
        // Connected to the port; now connect to MQTT Broker on this port
        struct mg_send_mqtt_handshake_opts opts;
        memset(&opts, 0, sizeof(opts));
        opts.user_name = NULL;
        opts.password = NULL;
        opts.keep_alive = 15;

        mg_set_protocol_mqtt(nc);
        mg_send_mqtt_handshake_opt(nc, "DemeterDJ1", opts);
        break;
    }
    case MG_EV_MQTT_CONNACK:
    {
        struct mg_mqtt_topic_expression topic = {"/#", 0};
        if (msg->connack_ret_code != MG_EV_MQTT_CONNACK_ACCEPTED)
        {
            printf("Got mqtt connection error: %d\n", msg->connack_ret_code);
            exit(1);
        }
        mqtt_nc = nc;
        mg_mqtt_subscribe(nc, &topic, 1, 2);
        is_subed = 0xFF;
        break;
    }
    case MG_EV_MQTT_PUBLISH:
    {
        char buf[1024] = "";

        strncat(buf, msg->payload.p, msg->payload.len);
        printf("Got %s\r\n", buf);
        break;
    }
    }
}

int main(void)
{
    struct mg_mgr mgr;
    const char *address = "0.0.0.0:54321";
    const char *s_address = "localhost:54321";
    struct mg_connection *broker_connection;
    struct mg_connection *tcp_connection;
    struct mg_mqtt_broker brk;

    time_t last = mg_time();

    mg_mgr_init(&mgr, NULL);
    mg_mqtt_broker_init(&brk, NULL);

    if ((broker_connection = mg_bind(&mgr, address, mg_mqtt_broker)) == NULL)
    {
        fprintf(stderr, "mg_bind(%s) failed\n", address);
        exit(EXIT_FAILURE);
    }
    broker_connection->user_data = &brk;

    mg_connect(&mgr, s_address, ev_handler);
    tcp_connection = mg_bind(&mgr, ":12345", ev_tcp_handler);

    printf("MQTT broker started on %s\n", address);

    int i = 0;

    for (;;)
    {
        mg_mgr_poll(&mgr, 1000);
        if (mg_time() - last > 1.4)
        {
            last = mg_time();
            if (mqtt_nc != NULL) {
                printf("%p vs %p vs %p\r\n", (void*)mqtt_nc, (void*)broker_connection, (void*)tcp_connection);
                printf("[%ld] MQTT Send Buffer length: %zi\r\n", last, mqtt_nc->send_mbuf.len);
                printf("[%ld] MQTT Send Broker Buffer length: %zi\r\n", last, broker_connection->send_mbuf.len);
                printf("[%ld] TCP Send Buffer length: %zi\r\n", last, tcp_connection->send_mbuf.len);
                printf("[%ld] MQTT Receive Buffer length: %zi\r\n", last, mqtt_nc->recv_mbuf.len);
                printf("[%ld] MQTT Receive Broker Buffer length: %zi\r\n", last, broker_connection->recv_mbuf.len);
                printf("[%ld] TCP Receive Buffer length: %zi\r\n", last, tcp_connection->recv_mbuf.len);
            }
            if (is_subed == 0xFF && i < 5) {
                char val[10] = "";
                sprintf(val, "%s%d", "val", i);
                printf("About to send %s\r\n", val);
                mg_mqtt_publish(mqtt_nc, "/test", 0, MG_MQTT_QOS(0), val, strlen(val));
                i++;
            }
        }
    }
}
```

**Comment by dimonomid** [comment] 2018-02-02 17:22
Can't reproduce with latest mongoose, closing.
Feel free to reopen if it's still an issue for you.

**Closed by dimonomid** 2018-02-02 17:22 UTC
