### ISSUE TITLE
Mongoose corrupting messages over websocket connections

### ISSUE THREAD

**Issue by HavenRemix** [cesanta/mongoose#1523] opened 2022-04-12 03:42 UTC
- My goal is: To consistently send data over a websocket connection.
- My expectation was: the messages would send normally
- The result I saw: 

```
client received: TESTING_MESSAGEüTESTING_MESSAGE
client received: TESTING_MESSAGE
```
when attempting to send TESTING_MESSAGE

and
```
client received: TESTING_MESSAGEü╡♠Θ→-uîtI+¥uü↨ANOTHER_TESTING_MESSAGEüJTESTING_MESSAGEü╡╠╩]1┐»3Uß╛2∟╝╕2R⌐╣.
á½(_»ó8Cßº<Xó±∟â₧§t₧ò   tƒ₧¶ïò►tƒÖ∟vëü↨ANOTHER_TESTING_MESSAGE
client received: ANOTHER_TESTING_MESSAGEüJTESTING_MESSAGEü╡╠╩]1┐»3Uß╛2∟╝╕2R⌐╣.
á½(_»ó8Cßº<Xó±∟â₧§t₧ò   tƒ₧¶ïò►tƒÖ∟vëü↨ANOTHER_TESTING_MESSAGE
client received: TESTING_MESSAGEü╡╠╩]1┐»3Uß╛2∟╝╕2R⌐╣.
á½(_»ó8Cßº<Xó±∟â₧§t₧ò   tƒ₧¶ïò►tƒÖ∟vëü↨ANOTHER_TESTING_MESSAGE
client received: ANOTHER_TESTING_MESSAGE
client received: TESTING_MESSAGEü╡α╫ß%ô▓ÅA═úÉÑÄFàñÆ▼î╢öKâ┐äW═║ÇLÄ∞ák»â⌐`▓ê╡`│â¿kºê¼`│äábÑü↨ANOTHER_TESTING_MESSAGEüCTESTING_MESSAGEü╡7¡MòD╚#±→┘"╕G▀"÷R▐>»[╠8√T┼(τ→└,ⁿYû
█x∙♣╨e≥↓╨d∙♦█p≥ü↨ANOTHER_TESTING_MESSAGE
client received: ANOTHER_TESTING_MESSAGEüCTESTING_MESSAGEü╡7¡MòD╚#±→┘"╕G▀"÷R▐>»[╠8√T┼(τ→└,ⁿYû
█x∙♣╨e≥↓╨d∙♦█p≥ü↨ANOTHER_TESTING_MESSAGE
client received: TESTING_MESSAGEü╡7¡MòD╚#±→┘"╕G▀"÷R▐>»[╠8√T┼(τ→└,ⁿYû
█x∙♣╨e≥↓╨d∙♦█p≥ü↨ANOTHER_TESTING_MESSAGE
client received: ANOTHER_TESTING_MESSAGE
client received: TESTING_MESSAGEü╡╗▄O╚k▓+ûz│b╦|│,▐}»u╫o⌐!╪f╣=ûc╜&╒5¥☺⌠Zö
ΘQê
ΦZò☺ⁿQæ
┐îó[ƒ½â4ûá₧?èáƒ4ù½ï?ôáƒ3ƒóëü↨ANOTHER_TESTING_MESSAGE♣░üß¶▒╚╝↕▒å⌐‼¡▀á☺½ï╗ùß
┐îó[ƒ½â4ûá₧?èáƒ4ù½ï?ôáƒ3ƒóëü↨ANOTHER_TESTING_MESSAGESSAGEü╡╠`▐σ┐♣░üß¶▒╚╝↕▒å⌐‼¡▀á☺½ï╗ùß
┐îó[ƒ½â4ûá₧?èáƒ4ù½ï?ôáƒ3ƒóëü↨ANOTHER_TESTING_MESSAGE¡▀á☺½ï╗ùß
client received: ANOTHER_TESTING_MESSAGE
client received: TESTING_MESSAGEü╡║+6.╔NXJù_Y♥╩YYM▀XE¶╓J
```
(there is a lot more...) when attempting to send TESTING_MESSAGE and ANOTHER_TESTING_MESSAGE without polling between the two.

- My question is: Why does this happen. If polling after a message is necessary, it is an easy fix, but what about the first issue. I couldn't find anything on google either.

# Environment

- mongoose version: latest
- Compiler/IDE and SDK: MSVC Visual Studio 2022
- Target hardware/board: Windows 11
- Connectivity chip/module: not sure, some intel network driver, I imagine

**Comment by cpq** [comment] 2022-04-12 08:45
@HavenRemix please share your code. Either make a separate github project, or create a PR with a failing unit test.

**Comment by cpq** [comment] 2022-04-13 10:15
Can't reproduce this, closing

**Closed by cpq** 2022-04-13 10:15 UTC
