### ISSUE TITLE
MG_EV_READ does not receive the last response chunk for "mg_http_connect" connection

### ISSUE THREAD

**Issue by Akshaykumar2002** [cesanta/mongoose#1375] opened 2021-10-11 09:31 UTC
- My goal is: _Write a proxy with support for both HTTP and HTTPS requests with some custom changes_
- My actions were:
I used the HTTP-reverse-proxy example to modify it to work for my specific URL. I made the following changes to test (patch provided below):
```
diff --git a/examples/http-reverse-proxy/main.c b/examples/http-reverse-proxy/main.c
index c6d7d32..61fd575 100644
--- a/examples/http-reverse-proxy/main.c
+++ b/examples/http-reverse-proxy/main.c
@@ -8,7 +8,7 @@
 // To enable SSL/TLS, build it like this:
 //    make MBEDTLS_DIR=/path/to/your/mbedtls/installation
 
-static const char *s_backend_url = "https://cesanta.com";
+static const char *s_backend_url = "http://www.google.com";
 static const char *s_listen_url = "http://localhost:8000";
 
 #include "mongoose.h"
@@ -41,6 +41,7 @@ static void forward_fn(struct mg_connection *c, int ev, void *ev_data, void *fn_
       mg_iobuf_del(&c->recv, 0, c->recv.len);
     }
   } else if (ev == MG_EV_CONNECT) {
+    c->is_hexdumping = 1;
     if (mg_url_is_ssl(s_backend_url)) {
       struct mg_tls_opts opts = {.ca = "ca.pem"};
       mg_tls_init(c, &opts);
@@ -55,7 +56,8 @@ static void fn(struct mg_connection *c, int ev, void *ev_data, void *fn_data) {
     struct mg_http_message *hm = (struct mg_http_message *) ev_data;
     // Client request, create backend connection Note that we're passing
     // client connection `c` as fn_data for the created backend connection.
-    c2 = mg_connect(c->mgr, s_backend_url, forward_fn, c);
+    c2 = mg_http_connect(c->mgr, s_backend_url, forward_fn, c);
+    c->is_hexdumping = 1;
     c->fn_data = c2;
 	
     if (c2 != NULL) {
@@ -77,9 +79,10 @@ static void fn(struct mg_connection *c, int ev, void *ev_data, void *fn_data) {
 int main(void) {
   struct mg_mgr mgr;
 
-  mg_log_set("3");                               // Set log level
+  mg_log_set("4");                               // Set log level
   mg_mgr_init(&mgr);                             // Initialise event manager
-  mg_http_listen(&mgr, s_listen_url, fn, NULL);  // Start proxy
+  struct mg_connection *c = mg_http_listen(&mgr, s_listen_url, fn, NULL);  // Start proxy
+  c->is_hexdumping = 1;
   for (;;) mg_mgr_poll(&mgr, 1000);              // Event loop
   mg_mgr_free(&mgr);
```
- My expectation was: `MG_EV_READ` of `forward_fn` would get the last MG_IO_BUF buffer via `*ev_data` and the curl request (request sent via curl client) would get the entire response.
- The result I saw: I see that it is not returning the complete HTTP response data. On investigation by changing the chunk size (`MG_IO_SIZE` value), I noticed that the last chunk of data is always lost. Upon investigation, I noticed that after `MG_EV_HTTP_MSG` is sent in `http_cb`, it attempts to delete the buffer.
```
mg_call(c, MG_EV_HTTP_MSG, &hm);
mg_iobuf_del(&c->recv, 0, hm.message.len);
```
I also noticed that when mg_call is done, it first calls `c->pfn` followed by the actual `c->fn`. I believe that due to this, that last chunk of data is somehow lost before it reaches `forward_fn` in the code.

 I am also not sure whether that mg_iobuf_del shown above is the right way to delete that specific buffer.
- My question is: Am I making the right changes? If yes, how do I fix this? Does it need a change in the library? Thanks!

# Environment

- mongoose version (e.g. 7.3): _7.4_
- Compiler/IDE (e.g. arm-none-eabi-gcc 9.3): _g++ 5.5.0 20171010_
- Target OS (e.g. FreeRTOS 10.3.1, Linux 5.8): _Ubuntu 16.04 LTS_

**Comment by cpq** [comment] 2021-10-30 11:11
@Akshaykumar2002 could you confirm that the latest codebase works as intended - and if yes, close the issue please?

**Closed** 2021-10-31 12:41 UTC
