### ISSUE TITLE
Fix for #2619 breaks fix for #2603

### ISSUE THREAD

**Issue by jcorporation** [cesanta/mongoose#2719] opened 2024-04-23 09:16 UTC
Sorry, that I must open a new issue regarding above issues.

- My goal is: Read post requests from a https socket issued by javascript
- My actions were: `MG_EV_HTTP_MSG with struct mg_http_message *hm = (struct mg_http_message *) ev_data`; as used in your examples
- My expectation was: mongoose reads the complete post data
- The result I saw: Reading large post data works with latest master, but reading small post data is failing. After reverting commit 3ac9bd0468969ae2d40bc84379c8038de6578355 reading small post data works, but reading large post data is failing. I tested this with your http-restful-server example. The issue appears only with enabled TLS (OpenSSL) and only with iPhone as a client, with my laptop browser there are no problems.
- My question is: No question, but it seems the fix for #2619 breaks fix for #2603.

# Environment

It is the same test environment as in #2619 and 2603.

- mongoose version: latest master
- Compiler/IDE and SDK: `gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3)`
- Target hardware/board: `Linux t14 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Client: iPhone (tested with safari and firefox mobile)

Attached a log with two post request. First is small request that is failing. Second is a bigger request that works.

[log.txt](https://github.com/cesanta/mongoose/files/15074305/log.txt)

**Comment by scaprile** [comment] 2024-04-23 14:43
@jcorporation Jürgen, can you please check #2720 ? (In both scenarios) Thank you !

@cpq : I think we've been going back and forth with two corner cases. Using "blame" I can see we've been using `mg_tls_pending()`, then resorted to `c->rtls.len` and then back to `mg_tls_pending()`.
I think there are two corner cases here:

- Msg is very short and gets sent along with the headers. `mg_tls_pending()` returns 0 as it has no data, BUT `c->rtls.len > 0` as there is outstanding data after parsing headers. That is #2603 , we fixed it but broke the next scenario
- Msg is of such a length that a whole block, or a group of them, fit the transfer. `c->rtls.len` is zero, BUT `mg_tls_pending()` will indicate it has a block to process. That seems to be #2619, its fix goes back to how things were before, causing a regression on the former scenario.

I merged both, and IIRC we've been there before, I remember some chat when we discussed whether both were necessary or not. I think this is real life answering us both.

**Comment by cpq** [comment] 2024-04-24 19:42
@scaprile thank you Sergio, makes sense!

**Closed** 2024-04-24 19:44 UTC
